/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Core.Product;
import Core.Ingredient;
import DAO.IngredientDAO;
import DAO.ProductDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author witoo
 */
public class AddUpdate_Dialog extends javax.swing.JDialog {
    private boolean isUpdate = false;
    private boolean isProduct = true;
    private CEO1 ceo;
    private ProductDAO productDAO;
    private IngredientDAO ingredientDAO;
    private Product previousProduct;
    private Ingredient previousIngredient;
    
    
    /**
     * Creates new form AddUpdate_Dialog
     */
    
    // Create a dialog to add a new product or ingredient
    public AddUpdate_Dialog(CEO1 ceo, boolean isProduct){  
        this(new javax.swing.JFrame(), true);
        this.ceo = ceo;
        this.isProduct = isProduct;
    }
    
    // Create a dialog to update a product
    public AddUpdate_Dialog(CEO1 ceo, Product previousProduct){
        this(new javax.swing.JFrame(), true);
        this.ceo = ceo;
        isUpdate = true;
        this.previousProduct = previousProduct;
        setTitle("Update Product");
        populateGui(previousProduct);
    }
    
    // Create a dialog to update an ingredient
    public AddUpdate_Dialog(CEO1 ceo, Ingredient previousIngredient){
        this(new javax.swing.JFrame(), true);
        this.ceo = ceo;
        isUpdate = true;
        isProduct = false;
        this.previousIngredient = previousIngredient;
        setTitle("Update Ingredient");
        populateGui(previousIngredient);
    }
    
    // Create a dialog
    public AddUpdate_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            productDAO = new ProductDAO();
            ingredientDAO = new IngredientDAO();
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    // Prepare the GUI for updating product
    public void populateGui(Product product){
        AddUpdate_Name_TextField.setText(product.getProName());
        AddUpdate_Amount_TextField.setText(Integer.toString(product.getStock()));   
    }
    
    // Prepare the GUI for updating ingredient
    public void populateGui(Ingredient ingredient){
        AddUpdate_Name_TextField.setText(ingredient.getIngName());
        AddUpdate_Amount_TextField.setText(Integer.toString(ingredient.getStock()));   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        AddUpdate_Name_TextField = new javax.swing.JTextField();
        AddUpdate_Amount_TextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Confirm_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Action_Logs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(88, 171, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel14.setText("Name");

        AddUpdate_Name_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUpdate_Name_TextFieldActionPerformed(evt);
            }
        });

        AddUpdate_Amount_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUpdate_Amount_TextFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel15.setText("Amount");

        Confirm_Button.setBackground(new java.awt.Color(255, 255, 255));
        Confirm_Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Confirm_Button.setText("Confirm");
        Confirm_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Confirm_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_ButtonActionPerformed(evt);
            }
        });

        Action_Logs.setColumns(20);
        Action_Logs.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Action_Logs.setRows(5);
        jScrollPane1.setViewportView(Action_Logs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddUpdate_Amount_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddUpdate_Name_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(Confirm_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddUpdate_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddUpdate_Amount_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Confirm_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddUpdate_Name_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUpdate_Name_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUpdate_Name_TextFieldActionPerformed

    private void AddUpdate_Amount_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUpdate_Amount_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUpdate_Amount_TextFieldActionPerformed

    private void Confirm_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_ButtonActionPerformed
        try{
            // Get the name of item
            String name = AddUpdate_Name_TextField.getText();
            int amount;
            
            // Didn't input item's name
            if(name == null || name.trim().length() == 0){
                JOptionPane.showMessageDialog(this, "Please input item's name.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Didn't input the amount
            if(AddUpdate_Amount_TextField.getText() == null || AddUpdate_Amount_TextField.getText().trim().length() == 0){
                JOptionPane.showMessageDialog(this, "Please input amount.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Get the amount of the item
            if(isNumeric(AddUpdate_Amount_TextField.getText())){
                amount = Integer.parseInt(AddUpdate_Amount_TextField.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Please input a number.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // The amount is negative
            if(amount < 0){
                JOptionPane.showMessageDialog(this, "Amount can't be less than 0.\nPlease input again.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // To update
            if(isUpdate){
                // Update a product
                if(isProduct){
                    productDAO.updateProduct(previousProduct.getProId(), name, amount);
                    ceo.refreshProductView();
                    ceo.refreshRecipeView();
                    setVisible(false);
                    dispose();
                    JOptionPane.showMessageDialog(ceo, "Product has been updated", "Product updated", JOptionPane.INFORMATION_MESSAGE);
                }
                // Update an ingredient
                else{
                    ingredientDAO.updateIngredient(previousIngredient.getIngId(), name, amount);
                    ceo.refreshIngredientView();
                    ceo.refreshRecipeView();
                    setVisible(false);
                    dispose();
                    JOptionPane.showMessageDialog(ceo, "Ingredient has been updated", "Ingredient updated", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            // To add a new item (Can add multiple items without closing this dialog)
            else{
                // Add a product
                if(isProduct){
                    //
                    productDAO.insertProduct(name, amount);
                    ceo.refreshProductView();
                }
                // Add an ingredient
                else{
                    ingredientDAO.insertIngredient(name, amount);
                    ceo.refreshIngredientView();
                }
                Action_Logs.setText(Action_Logs.getText() + name + " has been added.\n");
            }
            
        } catch(Exception exc){
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Confirm_ButtonActionPerformed
    
    // Check if the text can be converted to numbers
    public boolean isNumeric(String str){
        try {
            int num = Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUpdate_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUpdate_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUpdate_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUpdate_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddUpdate_Dialog dialog = new AddUpdate_Dialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Action_Logs;
    private javax.swing.JTextField AddUpdate_Amount_TextField;
    private javax.swing.JTextField AddUpdate_Name_TextField;
    private javax.swing.JButton Confirm_Button;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
