/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Core.Recipe;
import DAO.RecipeDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gurum
 */
public class UpdateRecipe_Dialog extends javax.swing.JDialog {
    private Recipe previousRecipe;
    private CEO1 ceo;
    private RecipeDAO recipeDAO;
    
    /**
     * Creates new form NewJDialog
     */
    
    // Create a dialog to update a recipe (used amount of an ingredient of this recipe)
    public UpdateRecipe_Dialog(CEO1 ceo, Recipe previousRecipe) {
        this(new javax.swing.JFrame(), true);
        try {
            this.previousRecipe = previousRecipe;
            this.ceo = ceo;
            recipeDAO = new RecipeDAO();
            populateGUI(previousRecipe);
            
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Create a dialog
    public UpdateRecipe_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    //  Prepare the GUI for updating the recipe
    public void populateGUI(Recipe previousRecipe){
        pro_name.setText(previousRecipe.getProName());
        ing_name.setText(previousRecipe.getIngName());
        Used_ingredient_amount.setText(Integer.toString(previousRecipe.getAmount()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pro_name = new javax.swing.JLabel();
        Used_ingredient_amount = new javax.swing.JTextField();
        Save_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ing_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Recipe");

        jPanel1.setBackground(new java.awt.Color(88, 171, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setInheritsPopupMenu(true);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("Product Name");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setText("Ingredient Amount Used");

        pro_name.setBackground(new java.awt.Color(255, 255, 255));
        pro_name.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        pro_name.setForeground(new java.awt.Color(255, 255, 255));
        pro_name.setText("pro_name");

        Used_ingredient_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Used_ingredient_amountActionPerformed(evt);
            }
        });

        Save_button.setBackground(new java.awt.Color(255, 255, 255));
        Save_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Save_button.setText("Save");
        Save_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setText("Ingredient Name");

        ing_name.setBackground(new java.awt.Color(255, 255, 255));
        ing_name.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        ing_name.setForeground(new java.awt.Color(255, 255, 255));
        ing_name.setText("ing_name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jLabel1))
                        .addComponent(jLabel3)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Used_ingredient_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pro_name)
                    .addComponent(ing_name))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pro_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ing_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Used_ingredient_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Used_ingredient_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Used_ingredient_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Used_ingredient_amountActionPerformed

    private void Save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_buttonActionPerformed
        try{
            int amount;
            // The CEO leave the field blank
            if(Used_ingredient_amount.getText() == null || Used_ingredient_amount.getText().trim().length() == 0){
                JOptionPane.showMessageDialog(this, "Please input amount.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Get the amount of ingredient
            if(ceo.isNumeric(Used_ingredient_amount.getText())){
                amount = Integer.parseInt(Used_ingredient_amount.getText());
            } else {    // There are characters in the amount field
                JOptionPane.showMessageDialog(this, "Please input a number.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //  The amount is negative
            if(amount <= 0){
                JOptionPane.showMessageDialog(this, "Amount can't be equal or less than 0.\nPlease input again.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Update the used amount of this ingredient
            recipeDAO.updateRecipe(previousRecipe.getRepId(), previousRecipe.getIngId(), amount);
            
            setVisible(false);
            dispose();
            
            ceo.refreshRecipeView();
            
            JOptionPane.showMessageDialog(ceo, "Recipe has been updated.", "Update Recipe", JOptionPane.INFORMATION_MESSAGE);
            
        } catch(Exception exc){
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Save_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipe_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipe_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipe_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipe_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateRecipe_Dialog dialog = new UpdateRecipe_Dialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save_button;
    private javax.swing.JTextField Used_ingredient_amount;
    private javax.swing.JLabel ing_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pro_name;
    // End of variables declaration//GEN-END:variables
}
